# Generated by Django 3.0.7 on 2020-06-13 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashCardApiImpl', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcard',
            name='flashCard_type',
            field=models.CharField(choices=[('CODE', 'Code'), ('TEXT', 'Text')], default='TEXT', max_length=4),
        ),
    ]
